#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "p5"
name = "p5.js"
description.en = "p5.js Editor is a website for creating p5.js sketches"
description.fr = "p5.js Editor est un site Web pour créer des croquis p5.js"

version = "2.16.7~ynh1"

maintainers = []

[upstream]
license = "LGPL-2.1"
website = "https://editor.p5js.org/"
demo = "https://editor.p5js.org/"
code = "https://github.com/processing/p5.js-web-editor"

[integration]

yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/processing/p5.js-web-editor/archive/refs/tags/v2.16.7.tar.gz"
    sha256 = "0a3562a1e1a5cc818df9b019476958d51e2408b2531b2e4d259621c3e407cc6e"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
