#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression "Loading installation settings..."

db_name=$(ynh_app_setting_get --key=db_name)
mongo_version=$(ynh_app_setting_get --key=mongo_version)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# If mongo_version doesn't exist, create it
if [ -z "$mongo_version" ]; then
    mongo_version="$(mongod --version | grep -oP 'db version v\K.{0,3}')"
    ynh_app_setting_set --key=mongo_version --value=$mongo_version
fi

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing nodejs..."

ynh_nodejs_install
ynh_hide_warnings ynh_install_mongo

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# Build
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
    ynh_hide_warnings ynh_exec_as_app npm install
    ynh_hide_warnings ynh_exec_as_app npm run build
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Coding tool for creativity" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
